### ISSUE TITLE
got-scraping not working with lambda function anymore

### ISSUE THREAD

**Issue by nrjdalal** [apify/got-scraping#147]
Cloudwatch logs -

```json
{
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, open '/var/task/dist//data_files/headers-order.json'",
    "code": "ENOENT",
    "errno": -2,
    "syscall": "open",
    "path": "/var/task/dist//data_files/headers-order.json",
    "stack": [
        "Error: ENOENT: no such file or directory, open '/var/task/dist//data_files/headers-order.json'",
        "    at Object.openSync (node:fs:573:18)",
        "    at readFileSync (node:fs:452:35)",
        "    at new HeaderGenerator (file:///var/task/dist/index.mjs:75050:62)",
        "    at file:///var/task/dist/index.mjs:88702:17",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)",
        "    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)",
        "    at async _tryAwaitImport (file:///var/runtime/index.mjs:1008:16)",
        "    at async _tryRequire (file:///var/runtime/index.mjs:1057:86)",
        "    at async _loadUserApp (file:///var/runtime/index.mjs:1081:16)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)"
    ]
}
```

Code ref -

https://github.com/nrjdalal/html-scraper

**Comment by B4nan** [comment]
What nodejs version are you on? This feels like a bug they introduced in v23.0.0, seeing the double slash in the path.

**Comment by nrjdalal** [comment]
INIT_START Runtime Version: nodejs:20.v42 Runtime Version

**Comment by nrjdalal** [comment]
if I comment out imports of got-scraping and usage, the fx works fine

**Comment by B4nan** [comment]
your project looks more like you are using bun, not nodejs?

**Comment by nrjdalal** [comment]
on aws I am using node only, there is no bun support, bun is for dev only

**Comment by Vrrl** [comment]
Same here, fresh lambda install, seems like the _dirname ends to be the lambda path instead of header-generator's one...

**Comment by zzzzaaa-000** [comment]
你的报错内容说明：

你的 AWS Lambda 或 Node.js 应用在 CloudWatch 日志中报错：
ENOENT: no such file or directory, open '/var/task/dist//data_files/headers-order.json'
这表示在代码运行环境中找不到 headers-order.json 这个文件，导致 fs.readFileSync 失败。
解决方案
1. 确认文件是否存在
检查你的本地项目中 dist/data_files/headers-order.json 是否真的存在。
如果有，是否被一并打包/部署到 Lambda 或其他云服务器环境下？
2. 打包和部署检查
如果你用的是 webpack、esbuild 等工具，有可能 json 文件没有被正确包含到最终的 dist/ 目录中。
解决方法：
确认 headers-order.json 被包含进你的 build/package。
对于 serverless/Lambda 部署，需要在 serverless.yml 或打包脚本中明确声明此文件为 artifact/resource。
例子（serverless.yml）:
yaml
package:
  include:
    - dist/data_files/headers-order.json
或者在 zip 打包时确保带上 json 文件。     具体回复在我的AI   https://code.mayoubang.cn/?_s=git-wz

**Comment by michael-pont** [comment]
I can confirm that I am receiving this error as well.
Any ideas on how to patch this error?
version: 4.1.1 and node version 22x

**Comment by nicklamonov** [comment]
Thanks everyone for your submissions!
We are aware of the issue and understand that it creates some inconveniences for you. 
Once we get to it after other priorities are resolved or find an alternative solution, we would report back.
