### ISSUE TITLE
Got-scraping throws error when trying to send a GET request to thetimes.co.uk

### ISSUE THREAD

**Issue by JaneJeon** [apify/got-scraping#54]
Minimum reproduction:

```js
import {gotScraping} from 'got-scraping'
await gotScraping('https://www.thetimes.co.uk/article/budget-2021-keir-starmer-faces-rebellion-for-stance-on-recovery-80tc5v2w3?shareToken=36c28cdcb70fc533d671f8ea20fb488b')
```

The error thrown is as follows:
```
Uncaught:
RequestError: The `options.agent` can be only an object `http`, `https` or `http2` properties
    at Request._beforeError (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-cjs/dist/source/core/index.js:325:21)
    at Request._onResponseBase (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-cjs/dist/source/core/index.js:707:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.module.exports [as auto] (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/http2-wrapper/source/auto.js:136:9)
    at options.request (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-scraping/dist/hooks/http2.js:14:36)
    at Request._makeRequest (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-cjs/dist/source/core/index.js:974:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Request._onResponseBase (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-cjs/dist/source/core/index.js:704:17)
    at async Request._onResponse (/Users/janejeon/Projects/JS/normalize-url-plus/node_modules/got-cjs/dist/source/core/index.js:772:13) {
  input: undefined,
  code: 'ERR_GOT_REQUEST_ERROR',
  timings: undefined,
  options: {
    request: [Function (anonymous)],
    agent: {
      http: TransformHeadersAgent { agent: [Agent] },
      https: TransformHeadersAgent { agent: [Agent] },
      http2: undefined
    },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: 60000,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: undefined,
    form: undefined,
    json: undefined,
    cookieJar: undefined,
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {
      headerGenerator: HeaderGenerator {
        defaultOptions: [Object],
        inputGeneratorNetwork: [BayesianNetwork],
        headerGeneratorNetwork: [BayesianNetwork]
      },
      useHeaderGenerator: true,
      insecureHTTPParser: true
    },
    hooks: {
      init: [
        [Function: optionsValidationHandler],
        [Function: customOptionsHook]
      ],
      beforeRequest: [
        [Function: http2Hook],
        [AsyncFunction: proxyHook],
        [AsyncFunction: browserHeadersHook],
        [Function: insecureParserHook]
      ],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: false,
    username: '',
    password: '',
    http2: true,
    allowGetBody: false,
    headers: {
      connection: 'keep-alive',
      'sec-ch-ua': '"Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"',
      'sec-ch-ua-mobile': '?0',
      'upgrade-insecure-requests': '1',
      dnt: '1',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0',
      accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
      'sec-fetch-mode': 'navigate',
      'sec-fetch-dest': 'document',
      'sec-fetch-site': 'same-site',
      'sec-fetch-user': '?1',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US',
      te: 'trailers'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 0,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'GET',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: false,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: 'TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: false,
    isStream: false,
    responseType: 'text',
    url: URL {
      href: 'http://www.thetimes.co.uk/tto/public/acs',
      origin: 'http://www.thetimes.co.uk',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'www.thetimes.co.uk',
      hostname: 'www.thetimes.co.uk',
      port: '',
      pathname: '/tto/public/acs',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined
  }
}
```

I would appreciate it if y'all could release a fix for this. I'm not sure why it's erroring out for this URL and not others, but it's clear it's got-scraping that has problem with this link, not some other component.

**Comment by szmarczak** [comment]
What's your `got-scraping` version? I believe it's fixed on latest

**Comment by JaneJeon** [comment]
Good question, looks like I was using an outdated version. Let me update it and see if it changes

**Comment by JaneJeon** [comment]
Fixed! Thanks
